authors:
  rc-sea:
    name: RC Carter
    description: RC Carter ran the ElectionGuard program as part of Microsoft's Democracy Forward program from 2018 to 2023.
    avatar: https://avatars.githubusercontent.com/u/12474675?v=4
    url: https://github.com/rc-sea