authors:
  rc-sea:
    name: RC Carter
    description: RC Carter is a longtime product person. Most recently, he ran the ElectionGuard program as part of Microsoft's Democracy Forward initiative from 2018 to 2023.
    avatar: https://avatars.githubusercontent.com/u/12474675?v=4
    url: https://github.com/rc-sea